definitions:
  models.ExamDetails:
    properties:
      academic_year:
        type: string
      college_name:
        type: string
      department_name:
        type: string
      exam_date:
        type: string
      exam_duration:
        type: string
      exam_end_time:
        type: string
      exam_instructions:
        items:
          type: string
        type: array
      exam_session:
        type: string
      exam_start_time:
        type: string
      exam_total_marks:
        type: string
      examination_name:
        type: string
      semester:
        type: string
      subject_code:
        type: string
      subject_name:
        type: string
    type: object
  models.GenerateQpaperSetsFromDBRequest:
    properties:
      exam_details:
        $ref: '#/definitions/models.ExamDetails'
      exam_type:
        type: string
      number_of_sets:
        type: integer
      q_paper_codes:
        items:
          type: string
        type: array
      subject_code:
        type: string
    type: object
  models.GenerateQpaperSetsInLatexRequest:
    properties:
      exam_details:
        $ref: '#/definitions/models.ExamDetails'
      number_of_sets:
        type: integer
      q_paper_codes:
        items:
          type: string
        type: array
      questions_by_type:
        items:
          $ref: '#/definitions/models.QuestionsByType'
        type: array
    type: object
  models.QuestionsByType:
    properties:
      choice_allowed:
        type: boolean
      marks:
        type: number
      questions:
        items:
          type: string
        type: array
      section_name:
        type: string
      total_questions:
        type: integer
      type_number:
        type: integer
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: qp gen service
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: qp gen service
  version: "1.0"
paths:
  /api/v1/generate-latex-q-paper-sets:
    post:
      description: Generate Q Paper Sets In Latex .tex format
      parameters:
      - description: request body
        in: body
        name: GenerateQPaperRequestsRequest
        required: true
        schema:
          $ref: '#/definitions/models.GenerateQpaperSetsInLatexRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - BearerAuth: []
      summary: Generate Q Paper Sets In Latex .tex format
      tags:
      - LATEX
  /api/v1/q-paper-from-db:
    post:
      description: Generate Q Paper Sets In Latex .tex format from db
      parameters:
      - description: request body
        in: body
        name: GenerateQpaperSetsFromDBRequest
        required: true
        schema:
          $ref: '#/definitions/models.GenerateQpaperSetsFromDBRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - BearerAuth: []
      summary: Generate Q Paper Sets In Latex .tex format from db
      tags:
      - DB
  /api/v1/upload/{academic_year}/{subject_code}:
    post:
      consumes:
      - multipart/form-data
      description: Upload Question Bank in CSV format
      parameters:
      - description: academic year
        in: path
        name: academic_year
        required: true
        type: string
      - description: subject code
        in: path
        name: subject_code
        required: true
        type: string
      - description: File to upload
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - BearerAuth: []
      summary: Upload Question Bank in CSV format
      tags:
      - Upload
securityDefinitions:
  BearerAuth:
    description: 'Enter the Bearer Authorization string as following: `Bearer Generated-JWT-Token`'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
